tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "black"
brew "clang-format"
brew "fzf"
brew "git"
brew "pyright"
brew "shellcheck"
brew "tmux"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-native-comp", "without-cocoa"]
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"
